spring:
    mail:
        host: smtp.gmail.com
        username: ******@gmail.com
        password: ******
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        